name:                ekisoba
version:             0.1.0.0
github:              "githubuser/ekisoba"
license:             BSD3
author:              "kitada"
maintainer:          "example@example.com"
copyright:           "2020 kitada"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ekisoba#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - language-c
  - text
  - aeson

executables:
  ekisoba-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ekisoba
    - language-c
    - aeson
    - aeson-pretty
    - bytestring
    - text

tests:
  ekisoba-test:
    main:                TestEkisoba.hs
    source-dirs:         test/Language/C
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ekisoba
    - HUnit
    - raw-strings-qq
    - text
    - temporary
    - language-c
    - aeson
    - aeson-pretty
